//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASG_Solution
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblImage
    {
        public int ID { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> Height { get; set; }
        public string AlternateText { get; set; }
        public string Extension { get; set; }
        public string ImageName { get; set; }
    }
}
